### ISSUE TITLE
Glance not working

### ISSUE THREAD

**Issue by tennyson-mccalla** [chamburr/glance#11]
### Environment

- **App version?**
- 1.4.1
- **macOS version?**
- 12.2.1

### Bug Information

- **What are you trying to do?**
- QuickLook some files (e.g. .ipynb, .py, .cpp, .c, .yaml)
- **What's the expected behavior?**
- A QuickLook window will open and show a preview of these files
- **What's the actual behavior?**
- A blank window
<img width="922" alt="Screen Shot 2022-02-12 at 09 32 13" src="https://user-images.githubusercontent.com/14319110/153715418-f56348a0-6dd0-4e47-b8b2-9dd92daf0b3a.png">

**Comment by chamburr** [comment]
Hey, I'm unable to reproduce this issue. Have you tried restarting your Mac?

**Comment by tennyson-mccalla** [comment]
I had not but I will when I try it again.
