### ISSUE TITLE
Extension com.chamburr.Glance.QLPlugin not found

### ISSUE THREAD

**Issue by aleexf** [chamburr/glance#12]
### Environment

- **App version?** 1.4.1
- **macOS version?** 12.2.1

### Bug Information

- **What are you trying to do?**
Preview any supported file
- **What's the expected behavior?**
Appears quicklook window with the file's content
- **What's the actual behavior?**
Appears quicklook window, but no content is displayed

<img width="573" alt="image" src="https://user-images.githubusercontent.com/25154338/154068084-a3e64c9c-b15b-4a7d-b614-7f36658956e8.png">

**Comment by chamburr** [comment]
Hello, this issue usually appears when Glance is not installed properly. Please try to delete /Applications/Glance.app and install again by follow the steps [here](https://github.com/chamburr/glance#installation). Let me know if this helped!

**Comment by aleexf** [comment]
Restart before installation fixed the problem. Now everything works fine. Thanks!

**Comment by robert-corlett** [comment]
You can also force the system to reload the quicklook generator list by running the following command:

`qlmanage -r`
