### ISSUE TITLE
Install QuickLook plugin without app ?

### ISSUE THREAD

**Issue by mrleblanc101** [chamburr/glance#15]
Hi, is there a way to install the QuickLook plugin without an app wrapper ?
I think this should be the default when using HomeBrew for exemple.
CLI usually install directly and do not require to have a separate app in the Application folder / Launchpad.
This could fix the self-signature problem for people using HomeBrew as I don't think QuickLook plugin require to be signed.
Also, I don't think you need a paid developer account for macOS Notarization, so if you notarize the app, I don't think people that have "Allow app from any developper" checked in Setting would have to do anything.

**Comment by chamburr** [comment]
There is currently no way to install the plugin without the app. I'm quite certain QuickLook plugins need to be notarized, and the option in preferences does not bypass the requirement either.
