### ISSUE TITLE
Big Sur Icon

### ISSUE THREAD

**Issue by mrleblanc101** [chamburr/glance#16]
Could the icon be updated to respect the new Guideline since Big Sur.
Squircle like on iOS.

**Comment by chamburr** [comment]
What do you think of this?
<img width="256" alt="Icon" src="https://user-images.githubusercontent.com/42373024/171377989-124284e8-02ef-4c2e-889f-fd9a851a87fd.png">

**Comment by mrleblanc101** [comment]
I think the concept of diagonal paper pages doesn't really exist in the current guideline, but I don't mind it.

**Comment by bpisano** [comment]
I opened #21 and provided multiple app icons.
