### ISSUE TITLE
Uninstallation process

### ISSUE THREAD

**Issue by KiF-78** [chamburr/glance#19]
Hi,
First, thank you for your work on Glance. 
I've an issue with PDF's previews... no morepreview, but not sure Glance is the problem. 
To make sure it's a Glance issue or not, do you have a complete uninstall process ?
Thank you in advance.
BR
F

**Comment by chamburr** [comment]
Hello, if you use an uninstallation tool like AppCleaner it would work well. Otherwise, you can delete the following files and directories manually.

```
/Applications/Glance.app
~/Library/Application Scripts/com.chamburr.Glance
~/Library/Application Scripts/com.chamburr.Glance.QLPlugin
~/Library/Containers/com.chamburr.Glance
~/Library/Containers/com.chamburr.Glance.QLPlugin
 ```

**Comment by KiF-78** [comment]
Thanks a lot !
AppCleaner is perfect.
BR
---
Franck
