### ISSUE TITLE
Support for [NFO]

### ISSUE THREAD

**Issue by FleXoft** [chamburr/glance#22]
- **What's the file's extension?**
.NFO .nfo

- **What's the file's Uniform Type Identifier (output of `mdls -name kMDItemContentType /path/to/your/file`)?**
Now it says this: kMDItemContentType = "org.planbnet.nfo"

- **What kind of preview do you expect? How can it be generated?**
Like this old one: https://github.com/planbnet/QuickNFO

**Comment by chamburr** [comment]
Not interested in supporting this due to complexity.
