### ISSUE TITLE
Not working in Ventura

### ISSUE THREAD

**Issue by nickriches** [chamburr/glance#28]
I can't get this to work in Ventura.

When I try to do a QuickLook of a markdown file I get the error message "Extension com.chamburr.Glance.QLPlugin not found".

Is this because glance has not been updated for Ventura yet? Or is there a fix?

Thanks

**Comment by chamburr** [comment]
Hello, Glance works in Ventura. Please see #12 for the solution to this error.

**Comment by nickriches** [comment]
Apologies. It has now started working. Not sure what happened here. Thanks for great app.
