### ISSUE TITLE
com.chamburr.Glance.QLPlugin failed during preview of this document.

### ISSUE THREAD

**Issue by frumbert** [chamburr/glance#29]
If I have quickview open on a document type that doesn't work at all such as .md (markdown) files, then move to another file type using the cursor keys, such as json, the preview for that json will show. If I then move off the file, then back again, the preview failed message appears and glance is now broken for all supported file types.

Re-opening Glance generally fixes it.

monterey 12.6.3 (21G419), m1
glance v1.5.0

**Comment by chamburr** [comment]
Cannot reproduce. Glance works fine on markdown files.
