### ISSUE TITLE
Support ".dart" file extension

### ISSUE THREAD

**Issue by lmapii** [chamburr/glance#32]
`glance` works really well out of the box!

I'd wonder if it is possible to add support for previewing other file types without having to update the app, e.g., I'd love to be able to just tell quicklook to treat a certain file as "text", in this case `.dart` files.

I don't need any code highlighting, however, I'd like to be able to preview `.dart` files. Would this be possible with `glance`?

**Comment by chamburr** [comment]
As far as I know, there is no way to change supported file types without updating the app. The list of file extensions must be stored in the Info.plist file, which cannot be changed dynamically.

You can see README on how to add a specific file extension. I believe `.dart` is already supported though, with syntax highlighting.
