### ISSUE TITLE
MEL (Maya Embedded Language) Support

### ISSUE THREAD

**Issue by Cuissedemouche** [chamburr/glance#37]
Hello,

I was wondering if it was possible to add a support for MEL, language used in Maya (one of the most used 3D software).
A highlight syntax would be a must but even opening it like a file text would be good.
MEL is syntactically similar to Perl and Tcl ([at least that what Wikipedia is saying](https://en.wikipedia.org/wiki/Maya_Embedded_Language)).

Thank you :)

**Comment by chamburr** [comment]
From testing, it looks like MEL is not sufficiently similar to Perl or Tcl to be properly supported. For similar reasons to #34, it would not be possible for us to add support for MEL directly.
