### ISSUE TITLE
Preview for Quarto .qmd files not working

### ISSUE THREAD

**Issue by joshbrake** [chamburr/glance#38]
I see on the Github readme that Quarto markdown files (`.qmd`) are supported but they don't seem to be working on my installation. I also noticed that they are not listed in the list of supported files in the app itself.

Are `.qmd` files supported and if so, is there something I need to do on my end to get them to work?
 
<img width="592" alt="image" src="https://github.com/chamburr/glance/assets/1339972/d5dba15c-f0b0-4682-8313-ef62b59e8d6d">

**Comment by chamburr** [comment]
Hi, I haven't released a version containing that feature. I'll try to do it soon.

**Comment by chamburr** [comment]
Sorry for the long wait! https://github.com/chamburr/glance/releases/tag/v1.5.1

**Comment by joshbrake** [comment]
Fantastic! Much appreciated @chamburr! This will be a great addition for me.
