### ISSUE TITLE
[Feature Request] Add new uncommon ext as a known ext (like `.in` but in fact it's a txt) from the app's ui

### ISSUE THREAD

**Issue by 15921483570** [chamburr/glance#39]
Sometimes I need to create a different ext for the files to distinguish them from the others, but the glance cannot be used then.

e.g.: The ext of data files for the OI / algorithm competition would usually be `.in` and `.out`, or`.in1`, `.in2`..., but they are in fact `.txt`.

I want to register these exts as txt so that I can glance them as txt, it's much easier than to change and build the source files.

I think it will be a useful function, thanks for your help!

**Comment by chamburr** [comment]
It is not possible to change the extensions supported from the UI. However, I think `.in` and `.out` would be reasonable defaults. Do you want to add them through a pull request? Example: https://github.com/chamburr/glance/pull/36/files
