### ISSUE TITLE
Can not quick look at .cpp and .ipynb

### ISSUE THREAD

**Issue by GJZ0117** [chamburr/glance#40]
Hello, I download the dmg file and install glance. It works on .java, .md, .py files.
However when I tried to quick look a .ipynb file, it displayed some error messages like this:

<img width="810" alt="image" src="https://github.com/chamburr/glance/assets/49833979/846eb7be-a75c-414e-a8bf-75388935029b">

When I tried to quick look a .cpp file, it displayed as the Mac default style:
<img width="575" alt="image" src="https://github.com/chamburr/glance/assets/49833979/80c65ac9-7886-488e-b071-00410cf8d20d">

I have restarted my Mac but it still cannot work. Do you have any solution?

**Comment by chamburr** [comment]
Hey, it would be really helpful if you could upload the files that don't work. I can't reproduce the issue based on the files I have on my computer.

**Comment by GJZ0117** [comment]
> Hey, it would be really helpful if you could upload the files that don't work. I can't reproduce the issue based on the files I have on my computer.

Sure, this is the .ipynb file and .cpp file.

I tested a new .ipynb file and find that if it only contains some easy statements like `print(time.time())`, it can be quick looked. So I guess maybe because I include too many third packages then it cannot be quick looked.

By the way, my environment is Macbook Pro M2Pro and the system version is 13.6.3.

[files.zip](https://github.com/chamburr/glance/files/13890025/files.zip)

**Comment by chamburr** [comment]
Your .cpp file cannot be parsed be parsed as UTF-8. Your .ipynb file does not appear to follow specifications (missing [] for the data section). We cannot support these cases.
