### ISSUE TITLE
Consider supporting plists?

### ISSUE THREAD

**Issue by YousufSSyed** [chamburr/glance#43]
It's not possible to edit a binary plist in a text editor and seems to require a dedicated plist editor. And it would be great to not need Xcode to edit plists, it's a slow and bloated app.

**Comment by chamburr** [comment]
Hi, macOS doesn’t support handling various file types, one of which is plist.

**Comment by YousufSSyed** [comment]
@chamburr Can u elaborate? Because I can change the default plist view in the Get Info window.
![CleanShot 2024-03-31 at 05 53 06@2x](https://github.com/chamburr/glance/assets/42646062/368a74d1-2c57-4e4f-aef6-a7e83b88756b)

**Comment by chamburr** [comment]
That is "Open with", which has nothing to do with preview.

**Comment by YousufSSyed** [comment]
Oh I see
