### ISSUE TITLE
CSV works but not TSV (I think)

### ISSUE THREAD

**Issue by mdaeron** [chamburr/glance#44]
I just reinstalled Glance v1.5.1, relaunched Finder, ran `qlmanage -r`, but quicklook does not seem to work with tsv files. For instance, the preview ai get for a csv file and the equivalent tsv are very different:

<img width="205" alt="Screen Shot 2024-04-20 at 15 50 14 " src="https://github.com/chamburr/glance/assets/33901276/dc993f85-1297-4f91-ab93-d17b83433b9b">

<img width="215" alt="Screen Shot 2024-04-20 at 15 49 57 " src="https://github.com/chamburr/glance/assets/33901276/6306336b-1d76-4e31-bebc-7b006cf802c9">

Is this the expected behavior or am I missing something?

**Comment by chamburr** [comment]
Preview for csv is not handled by Glance, so this should be the expected behaviour.

I get this with the example file in GlanceTests:
![](https://github.com/user-attachments/assets/b3f31171-3249-432b-a7f0-2fb294c2cf7e)
