### ISSUE TITLE
[BUG] QuickLook preview cut in half

### ISSUE THREAD

**Issue by gmcinalli** [chamburr/glance#8]
### Environment

- **App version?**
1.4.0

- **macOS version?**
12.0.1

### Bug Information

- **What are you trying to do?**
Use Glance for what it was written for.

- **What's the expected behavior?**
Glance should show me the preview of the code in QuickLook.

- **What's the actual behavior?** 
The previews of each type of file supported by Glance open as per the attached screenshots.

![image](https://user-images.githubusercontent.com/9024983/141799702-e17b8e28-f7bf-4107-a86a-21c85acf80ff.png)
![image](https://user-images.githubusercontent.com/9024983/141799732-fb61798e-3062-4005-bf40-30f2069df7a5.png)
![image](https://user-images.githubusercontent.com/9024983/141799785-0e3d77a8-15f4-447a-b3bd-3888919ff446.png)

**Comment by EmaadKhwaja** [comment]
been having the same issue

**Comment by chamburr** [comment]
Sorry for the long wait. The issue is fixed now!
